import { Project } from "@/Interface/projects";

export const projects: Project[] = [
  {
    slug: "mern-chat-app",
    title: "MERN - ChatApp",
    brief: "A real-time chat application built with the MERN stack (MongoDB, Express.js, React, Node.js). The app features user authentication, private messaging, and socket-based communication for instant updates. Styled with Tailwind CSS and powered by Socket.IO for seamless real-time interaction across clients.",
    description:
      "A real-time chat application built with the MERN stack, featuring instant messaging, user auth, and socket-based communication.",
    images: [
      "mern-chat-app-1.png",
      "mern-chat-app-2.png",
      "mern-chat-app-3.png",
      "mern-chat-app-4.png",
      "mern-chat-app-5.png",
    ],
    stack: [
      "MongoDB",
      "Express.js",
      "React.js",
      "Node.js",
      "Tailwind",
      "Daisy UI",
    ],
    url: "https://chat-gxve.onrender.com/",
    repository: "https://github.com/furqanahmad03/MERN-ChatApp",
  },
  {
    slug: "remix-electron-cli",
    title: "Remix-Electron-Cli",
    brief: "A cross-platform desktop app built with Electron and Remix (Vite) for the frontend and FastAPI (Python) for the backend. The app launches a local web server and opens a desktop window using Electron, serving the Remix UI while interacting with a Python API. Chakra UI and Recharts used for styling components and plotting graphs.",
    description:
      "A desktop app using Electron, Remix (Vite), and FastAPI that runs a local server and connects a React UI to a Python API.",
    images: [
      "remix-cli-1.png",
      "remix-cli-2.png",
      "remix-cli-3.png",
      "remix-cli-4.png",
      "remix-cli-5.png",
      "remix-cli-6.png",
    ],
    stack: [
      "Remix",
      "Electron.js",
      "React.js",
      "Typescript",
      "Tailwind",
      "Chakra UI",
      "Recharts",
      "FastAPI"
    ],
    url: "",
    repository: "https://github.com/furqanahmad03/remix-electron-cli",
  },
  {
    slug: "ai-image-generator",
    title: "MERN - AI Image Generator",
    brief: "A full-stack web application built with the MERN stack that allows users to generate and explore AI-generated images based on text prompts. It features user-friendly search functionality, real-time loading indicators, and responsive UI. If the OpenAI API is unavailable, the app gracefully falls back to sample images for a smooth experience.",
    description:
      "A web application that generates images using OpenAI and displays all the generated images.",
    images: [
      "AIIG-1.png",
      "AIIG-2.png",
      "AIIG-3.png",
      "AIIG-4.png",
    ],
    stack: [
      "HTML",
      "CSS",
      "Javascript",
      "React.js",
      "Tailwind",
      "Material UI",
      "Typescript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "OpenAI DALL·E API",
      "Cloudinary",
    ],
    url: "",
    repository: "https://github.com/furqanahmad03/MERN-AI-Image-Generation",
  },
  {
    slug: "issue-tracker",
    title: "Next.js Issue Tracker",
    brief: "Developed an issue-tracking application using Next.js and TypeScript, featuring user authentication and a dashboard with visual charts like pie and bar graphs. The app enables users to create, edit, assign, and categorize issues as OPEN, IN_PROGRESS, or CLOSED. It uses MySQL for data management, ensuring reliable storage and seamless data handling.",
    description:
      "A web application that helps you to organize your issues.",
    images: [
      "issue-1.png",
      "issue-2.png",
      "issue-3.png",
      "issue-4.png",
      "issue-5.png",
    ],
    stack: [
      "HTML",
      "CSS",
      "Javascript",
      "React.js",
      "Tailwind",
      "Radix.UI",
      "Typescript",
      "Node.js",
      "Next.js",
      "MySQL",
      "NextAuth.js"
    ],
    url: "",
    repository: "https://github.com/furqanahmad03/java-gorcery-store",
  },
  {
    slug: "grocery-store",
    title: "Java Grocery Store",
    brief: "Developed a Java-based online grocery store with user authentication, product management, and order tracking. Features include admin and customer login, product search, cart management, order placement, and session handling. Admins manage products, while customers browse, add to cart, and track orders.",
    description:
      "A grocery store with all the functionalities of User and Admin tasks.",
    images: [
      "grocery-store-1.png",
      "grocery-store-2.png",
      "grocery-store-3.png",
      "grocery-store-4.png",
      "grocery-store-5.png",
      "grocery-store-6.png",
      "grocery-store-7.png",
      "grocery-store-8.png",
    ],
    stack: [
      "HTML",
      "CSS",
      "Javascript",
      "Bootstrap",
      "Java",
    ],
    url: "",
    repository: "https://github.com/furqanahmad03/java-gorcery-store",
  },
  {
    slug: "weather-app",
    title: "Weather App",
    brief: "Developed a weather app with enhanced UI to display every sort of information regarding weather. Developed using HTML, CSS, Tailwind and JavaScript. The app displays current weather conditions and stores previous searches for easy comparison.",
    description:
      "A platform for searching the current weather.",
    images: [
      "weather-app-1.png",
      "weather-app-2.png",
    ],
    stack: [
      "HTML",
      "CSS",
      "Javascript",
      "Tailwind",
    ],
    url: "https://weather-forecast2-by-furqan.vercel.app/",
    repository: "https://github.com/furqanahmad03/weather-app",
  },
  {
    slug: "weather-forecast",
    title: "Weather Forecast",
    brief: "Developed a weather app using HTML, CSS, Tailwind and JavaScript. The app displays current weather conditions and stores previous searches for easy comparison.",
    description:
      "A platform for searching the current weather.",
    images: [
      "weather-forecast-1.png",
      "weather-forecast-2.png",
      "weather-forecast-3.png",
    ],
    stack: [
      "HTML",
      "CSS",
      "Javascript",
      "Tailwind",
    ],
    url: "https://weather-forecast-by-furqan.vercel.app/",
    repository: "https://github.com/furqanahmad03/weather-forecast",
  },
];
